version: '3'
services:
  ethereumnode1:
    hostname: ethereumnode1
    image: ethereum/client-go:alpine
    ports:
      - '30303:30303'
      - '8545:8545'
    volumes:
      - 0:/eth
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /eth/geth
        /geth \
        --identity "ethereumnode1" \
        --dev \
        --rpc \
        --rpcaddr "0.0.0.0" \
        --rpcport "8545" \
        --rpccorsdomain "*" \
        --datadir "/eth" \
        --port "30303" \
        --rpcapi "db,eth,net,web3,personal,admin" \
        --networkid "333" \
        --nat "any" \
        --mine \
        --minerthreads 1 \
        --nodiscover \
        --debug \
        --metrics \
        --syncmode "full" \
        --gasprice 0
        sleep 300000
    networks:
      app_net:
        ipv4_address: 172.16.239.10
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
volumes:
  "0":


